# permissions for end users to view floppybirds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: floppybird-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: floppybird-operator-demo
    app.kubernetes.io/part-of: floppybird-operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: floppybird-viewer-role
rules:
- apiGroups:
  - webapp.demo.viadee.de
  resources:
  - floppybirds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.demo.viadee.de
  resources:
  - floppybirds/status
  verbs:
  - get
