name: Build floppy bird distro

# run action on change in direcoty hack/floppy-distro-image
on:
  push:
    paths:
      - "hack/floppy-distro-image/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_PROD_ECR_VIADEE_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_PROD_ECR_VIADEE_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
