name: Build floppy bird distro

# run action on change in directory hack/floppy-distro-image
on:
  push:
    paths:
      - "hack/floppy-distro-image/**"
      - ".github/workflows/image-floppydistros.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_PROD_ECR_VIADEE_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_PROD_ECR_VIADEE_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:hack/floppy-distros-image"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            public.ecr.aws/viadee/floppybird-demo
